[[declaring-dependency-versions]]
= Declaring dependency versions

[[rich-version-constraints]]
== Rich version declarations

Gradle supports a rich model for declaring versions, which allows to combine different level of version information.
The terms and their meaning are explained below, from the strongest to the weakest:

`strictly`::
Any version not matched by this version notation will be excluded.
This is the strongest version declaration.
It will cause dependency resolution to fail if no version acceptable by this clause can be selected.
This term supports dynamic versions.
+
When defined, overrides previous `require` declaration and clears previous `reject`.

`require`::
Implies that the selected version cannot be lower than what `require` accepts but could be higher through conflict resolution, even if higher has an exclusive higher bound.
This is what a direct version on a dependency translates to.
This term supports dynamic versions.
+
When defined, overrides previous `strictly` declaration and clears previous `reject`.

`prefer`::
This is a very soft version declaration.
It applies only if there is no stronger non dynamic opinion on a version for the module.
This term does not support dynamic versions.
+
Definition can complement `strictly` or `require`.

There is also an additional term outside of the level hierarchy:

`reject`::
Declares that specific version(s) are not accepted for the module.
This will cause dependency resolution to fail if the only versions selectable are also rejected.
This term supports dynamic versions.

The following table illustrates a number of use cases and how to combine the different terms for rich version declaration:

.Rich version use cases
[%header%autowidth,compact]
|===
| Which version(s) of this dependency are acceptable? | `strictly` | `require` | `prefer` | `rejects` | Selection result

| Tested with version `1.5`, believe all future versions should work
|
| 1.5
|
|
| Any version starting from `1.5`, equivalent of `org:foo:1.5`. An upgrade to `2.4` is accepted.

| Tested with `1.5`, soft constraint upgrades according to semantic versioning
|
| [1.0, 2.0[
| 1.5
|
| Any version between `1.0` and `2.0`, `1.5` if nobody else cares. An upgrade to `2.4` is accepted. +
🔒

| Tested with `1.5`, but follows semantic versioning
| [1.0, 2.0[
|
| 1.5
|
| Any version between `1.0` and `2.0` excluded, `1.5` if nobody else cares. +
🔒

| Same as above, with `1.4` known broken
| [1.0, 2.0[
|
| 1.5
| 1.4
| Any version between `1.0` and `2.0` excluded except for `1.4`, `1.5` if nobody else cares. +
🔒

| No opinion, works with `1.5`
|
|
| 1.5
|
| `1.5` if no other opinion, any otherwise

| No opinion, prefer latest release
|
|
| `latest.release`
|
| The latest release at build time +
🔒

| On the edge, latest release, no downgrade
|
| `latest.release`
|
|
| The latest release at build time +
🔒

| No other version than 1.5
| 1.5
|
|
|
| 1.5, or failure if another `strict` or higher `require` constraint disagrees

| `1.5` or a patch version of it exclusively
| [1.5,1.6[
|
|
|
| Latest `1.5.x` patch release, or failure if another `strict` or higher `require` constraint disagrees +
🔒
|===

Lines annotated with a lock (🔒) indicate that leveraging <<dependency_locking.adoc#,dependency locking>> makes sense in this context.
Another concept that relates with rich version declaration is the ability to publish <<publishing_maven.adoc#publishing_maven:resolved_dependencies,resolved versions>> instead of declared ones.


Using `strictly`, especially for a library, must be a well thought process as it can have a serious impact on downstream consumers.
At the same time, used correctly, it will help consumers understand what combination of libraries do not work together in their context.


[NOTE]
====
Rich version information will be preserved when using the Gradle metadata format.
However conversion to Ivy or Maven metadata formats will be lossy.
The highest level will be published, that is `strictly` or `require` over `prefer`.
In addition, any `reject` will be ignored.
====

Rich version declaration is accessed through the `version` DSL method on a dependency or constraint declaration which gives access to link:{javadocPath}/org/gradle/api/artifacts/MutableVersionConstraint.html[MutableVersionConstraint].

.Rich version declaration
====
include::sample[dir="userguide/dependencyManagement/declaringDependencies/concreteVersion/groovy",files="build.gradle[tags=rich-version]"]
include::sample[dir="userguide/dependencyManagement/declaringDependencies/concreteVersion/kotlin",files="build.gradle.kts[tags=rich-version]"]
====

[[dynamic-versions]]
== Dynamic versions

[[controlling-dynamic-version-caching]]
=== Controlling dynamic version caching

[[component-selection-rules]]
=== Component selection rules

[[refreshing-dependencies]]
=== Refreshing dependencies

[[dealing-with-changing-versions]]
== Dealing with changing versions

[[dependency-locking]]
=== Dependency locking

Use of dynamic dependency versions (e.g. `1.+` or `[1.0,2.0)`) makes builds non-deterministic.
This causes builds to break without any obvious change, and worse, can be caused by a transitive dependency that the build author has no control over.

To achieve https://reproducible-builds.org/[reproducible builds], it is necessary to _lock_ versions of dependencies and transitive dependencies such that a build with the same inputs will always resolve the same module versions.
This is called _dependency locking_.

It enables, amongst others, the following scenarios:

* Companies dealing with multi repositories no longer need to rely on `-SNAPSHOT` or changing dependencies,
which sometimes result in cascading failures when a dependency introduces a bug or incompatibility.
Now dependencies can be declared against major or minor version range, enabling to test with the latest versions on CI while leveraging locking for stable developer builds.
* Teams that want to always use the latest of their dependencies can use dynamic versions, locking their dependencies only for releases.
The release tag will contain the lock states, allowing that build to be fully reproducible when bug fixes need to be developed.

Combined with <<publishing_maven.adoc#publishing_maven:resolved_dependencies,publishing resolved versions>>, you can also replace the declared dynamic version part at publication time.
Consumers will instead see the versions that your release resolved.

Locking is enabled per <<managing_dependency_configurations.adoc#managing_dependency_configurations,dependency configuration>>.
Once enabled, you must create an initial lock state.
It will cause Gradle to verify that resolution results do not change, resulting in the same selected dependencies even if newer versions are produced.
Modifications to your build that would impact the resolved set of dependencies will cause it to fail.
This makes sure that changes, either in published dependencies or build definitions, do not alter resolution without adapting the lock state.

[NOTE]
====
Dependency locking makes sense only with <<declaring_dependencies.adoc#sub:declaring_dependency_with_dynamic_version,dynamic versions>>.
It will have no impact on <<declaring_dependencies.adoc#sub:declaring_dependency_with_changing_version,changing versions>> (like `-SNAPSHOT`) whose coordinates remain the same, though the content may change.
Gradle will even emit a warning when persisting lock state and changing dependencies are present in the resolution result.
====

=== Enabling locking on configurations

Locking of a configuration happens through the link:{groovyDslPath}/org.gradle.api.artifacts.ResolutionStrategy.html[ResolutionStrategy]:

.Locking a specific configuration
====
include::sample[dir="userguide/dependencyManagement/dependencyLocking/lockingSingleConfiguration/groovy",files="build.gradle[tags=locking-one]"]
include::sample[dir="userguide/dependencyManagement/dependencyLocking/lockingSingleConfiguration/kotlin",files="build.gradle.kts[tags=locking-one]"]
====

Or the following, as a way to lock all configurations:

.Locking all configurations
====
include::sample[dir="userguide/dependencyManagement/dependencyLocking/lockingAllConfigurations/groovy",files="build.gradle[tags=locking-all]"]
include::sample[dir="userguide/dependencyManagement/dependencyLocking/lockingAllConfigurations/kotlin",files="build.gradle.kts[tags=locking-all]"]
====

[NOTE]
====
Only configurations that can be resolved will have lock state attached to them.
Applying locking on non resolvable-configurations is simply a no-op.
====

[NOTE]
====
The above will lock all _project_ configurations, but not the _buildscript_ ones.
====

=== Locking buildscript classpath configuration

If you apply plugins to your build, you may want to leverage dependency locking there as well.
In order to lock the <<plugins.adoc#sec:applying_plugins_buildscript,`classpath` configuration>> used for script plugins, do the following:

.Locking buildscript classpath configuration
====
include::sample[dir="userguide/dependencyManagement/dependencyLocking/lockingClasspathConfiguration/groovy",files="build.gradle[tags=locking-classpath]"]
include::sample[dir="userguide/dependencyManagement/dependencyLocking/lockingClasspathConfiguration/kotlin",files="build.gradle.kts[tags=locking-classpath]"]
====

=== Generating and updating dependency locks

In order to generate or update lock state, you specify the `--write-locks` command line argument in addition to the normal tasks that would trigger configurations to be resolved.
This will cause the creation of lock state for each resolved configuration in that build execution.
Note that if lock state existed previously, it is overwritten.

==== Lock all configurations in one build execution

When locking multiple configurations, you may want to lock them all at once, during a single build execution.

For this, you have two options:

* Run `gradle dependencies --write-locks`.
This will effectively lock all resolvable configurations that have locking enabled.
Note that in a multi project setup, `dependencies` only is executed on _one_ project, the root one in this case.
* Declare a custom task that will resolve all configurations

.Resolving all configurations
====
include::sample[dir="userguide/dependencyManagement/dependencyLocking/lockingAllConfigurations/groovy",files="build.gradle[tags=resolve-all]"]
include::sample[dir="userguide/dependencyManagement/dependencyLocking/lockingAllConfigurations/kotlin",files="build.gradle.kts[tags=resolve-all]"]
====

That second option, with proper choosing of configurations, can be the only option in the native world, where not all configurations can be resolved on a single platform.

=== Lock state location and format

Lock state will be preserved in a file located in the folder `gradle/dependency-locks` inside the project or subproject directory.
Each file is named by the configuration it locks and has the `lockfile` extension.
The one exception to this rule is for configurations for the <<plugins.adoc#sec:applying_plugins_buildscript,buildscript itself>>.
In that case the configuration name will be prefixed with `buildscript-`.

The content of the file is a module notation per line, with a header giving some context.
Module notations are ordered alphabetically, to ease diffs.

.Lockfile content
[listing]
.gradle/dependency-locks/compileClasspath.lockfile
----
include::{samplesPath}/userguide/dependencyManagement/dependencyLocking/lockingSingleConfiguration/groovy/gradle/dependency-locks/compileClasspath.lockfile[]
----

which matches the following dependency declaration:

.Dynamic dependency declaration
====
include::sample[dir="userguide/dependencyManagement/dependencyLocking/lockingSingleConfiguration/groovy",files="build.gradle[tags=locking-deps]"]
include::sample[dir="userguide/dependencyManagement/dependencyLocking/lockingSingleConfiguration/kotlin",files="build.gradle.kts[tags=locking-deps]"]
====

=== Running a build with lock state present

The moment a build needs to resolve a configuration that has locking enabled and it finds a matching lock state,
it will use it to verify that the given configuration still resolves the same versions.

A successful build indicates that the same dependencies are used as stored in the lock state, regardless if new versions matching the dynamic selector have been produced.

The complete validation is as follows:

* Existing entries in the lock state must be matched in the build
** A version mismatch or missing resolved module causes a build failure
* Resolution result must not contain extra dependencies compared to the lock state

=== Selectively updating lock state entries

In order to update only specific modules of a configuration, you can use the `--update-locks` command line flag.
It takes a comma (`,`) separated list of module notations.
In this mode, the existing lock state is still used as input to resolution, filtering out the modules targeted by the update.

----
❯ gradle classes --update-locks org.apache.commons:commons-lang3,org.slf4j:slf4j-api
----

Wildcards, indicated with `*`, can be used in the group or module name. They can be the only character or appear at the end of the group or module respectively.
The following wildcard notation examples are valid:

* `org.apache.commons:*`: will let all modules belonging to group `org.apache.commons` update
* `*:guava`: will let all modules named `guava`, whatever their group, update
* `org.springframework.spring*:spring*`: will let all modules having their group starting with `org.springframework.spring` and name starting with `spring` update

[NOTE]
====
The resolution may cause other module versions to update, as dictated by the Gradle resolution rules.
====

=== Disabling dependency locking

. Make sure that the configuration for which you no longer want locking is not configured with locking.
. Remove the file matching the configurations where you no longer want locking.

If you only perform the second step above, then locking will effectively no longer be applied.
However, if that configuration happens to be resolved in the future at a time where lock state is persisted, it will once again be locked.

[[locking_limitations]]
=== Locking limitations

* Locking can not yet be applied to source dependencies.

=== Nebula locking plugin

This feature is inspired by the https://github.com/nebula-plugins/gradle-dependency-lock-plugin[Nebula Gradle dependency lock plugin].

